### ISSUE TITLE
Review my rework

### ISSUE THREAD

**Issue by phuonghuynh** [phuonghuynh/tips-calculator#1]
/cc @coderschoolreview

**Comment by avo1** [comment]
Hi @phuonghuynh ,

Thanks for submission. Good job with Tip Calculator 👍 

### Quick Comments:

- Good usage of `NSUserDefaults`. This is one of the methods to pass the data from multiple viewController. We will learn few more ways to do that. However when you go back from Setting screen, you will want to change the default tip percentage at main screen. The code will be in main screen `viewWillAppear`
- Similar thing can be done to save the bill amount. Look at the `NSDate()` to calculate the time because we only want to save the amount if the app restart within 10min.
- Your keyboard doesn't have the decimal point then user can't enter something like `100.5`. You can change the keyboard style to `DecimalPad`.

### Optional Suggestions to Improve

* Look into the `UIView.animateWithDuration` functions to add animations.
* You can show the keyboard immediately when app starts by using `becomeFirstResponder`
* Try `NSNumberFormatter` and `CurrencyStyle` for to format the currency.


Regards,
Dave

**Comment by phuonghuynh** [comment]
Thanks @avo1 for your comments, do i need to fix them to pass the pre-work ?

**Comment by coderschoolreview** [comment]
It's good to go. We'll email you the class info.

**Comment by phuonghuynh** [comment]
closed
